INSERT INTO TASK_CATEGORIES (NAME, DESCRIPTION)
SELECT 'Work', 'Tasks related to work'
WHERE NOT EXISTS (
    SELECT 1 FROM TASK_CATEGORIES WHERE NAME = 'Work'
);

INSERT INTO TASK_CATEGORIES (NAME, DESCRIPTION)
SELECT 'Home', 'Tasks related to home activities'
WHERE NOT EXISTS (
    SELECT 1 FROM TASK_CATEGORIES WHERE NAME = 'Home'
);

INSERT INTO TASKS (NAME, DESCRIPTION, DEADLINE, CATEGORY_ID)
SELECT 'Complete report', 'Annual financial report completion', '2024-02-15 17:00:00', CAT.ID
FROM TASK_CATEGORIES CAT
WHERE CAT.NAME = 'Work'
AND NOT EXISTS (
    SELECT 1 FROM TASKS WHERE NAME = 'Complete report'
);

INSERT INTO TASKS (NAME, DESCRIPTION, DEADLINE, CATEGORY_ID)
SELECT 'Fix sink', 'Repair the leaking sink in the bathroom', '2024-03-01 12:00:00', CAT.ID
FROM TASK_CATEGORIES CAT
WHERE CAT.NAME = 'Home'
AND NOT EXISTS (
    SELECT 1 FROM TASKS WHERE NAME = 'Fix sink'
);
